### ISSUE TITLE
Revisión de proyecto

### ISSUE THREAD

**Issue by mikenieva** [RaquelGlez/core-am-cipher#1]
Raquel,

- Me gustó mucho tu estructura y documentación. En general no tienes ningún error de sintaxis en tu código y el cipher funciona.

- Donde puedes mejorar es en la validación del W3, en el cual pones tu dirección URL del proyecto ahí y vas revisando los errores. https://validator.w3.org/

- Con respecto a los tests, buena ejecución. Faltó el último pero en general, el desarrollo lo hiciste bien.

- Veo que ya no hiciste la parte del Responsive Web Design. Intenta desarrollarlo. Haría más fuerte tu proyecto.

- Finalmente, la parte UX no la descuides. Siempre que desarrolles un proyecto haz la investigación del usuario. Te hará mejor desarrolladora y podrás darle más fuerza a todo lo que construyas.

Buen proyecto, Raquel. Atento de tus comentarios.

**Comment by RaquelGlez** [comment]
Gracias por tus comentarios Mike, pondré atención a cada uno e intentare mejorar mi proyecto.
